name = "VectorizedReduction"
uuid = "4ffe575c-65e5-43f4-bc05-e0b500dc3d2c"
authors = ["Andrew J. Radcliffe <andrewjradcliffe@gmail.com"]
version = "0.1.9"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
LoopVectorization = "0.12.108"
Static = "0.7, 0.8"
julia = "1.5 - 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
